ulo/comments/urls.py
"""
Comments URL Configuration
"""

# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------

# Standard library imports
from __future__ import unicode_literals

# Core django imports
from django.conf.urls import include, url

# Thrid party app imports

# Project imports
from . import views

# ----------------------------------------------------------------------------------------




# ----------------------------------------------------------------------------------------

urlpatterns = [

	# Comment actions menu when JS is disabled
	url(r'^(?P<pk>[\d]+)/actions/$', views.CommentActionsView.as_view(), name='comment_actions'),

	# Report this comment.
	url(r'^report/complete/$', views.CommentReportCompleteView.as_view(), name='comment_report_complete'),
	url(r'^(?P<pk>[\d]+)/report/$', views.CommentReportView.as_view(), name='comment_report'),

	# Delete this comment
	url(r'^(?P<pk>[\d]+)/delete/$', views.CommentDeleteView.as_view(), name='comment_delete')

]

# ----------------------------------------------------------------------------------------

ulo/config/urls.py
# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------

# Standard library imports

# Core django imports
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

# Thrid party app imports

# Project imports
from generics.views import HomeAuthView, NavigationView
from users.views import LoginView, LogoutView, SignUpView

# TO SERVE MEDIA FILES IN DEVELOPMENT ONLY
from django.conf.urls.static import static

# ----------------------------------------------------------------------------------------




# ----------------------------------------------------------------------------------------

urlpatterns = [

	# TESTING!!!!
	url(r'^search/', include('search.urls', namespace='search')),


	# Landing Page
	url(r'^$', HomeAuthView.as_view(), name='home'),


	# User Posts (Post detail, Post form)
	url(r'^post/', include('posts.urls', namespace='posts')),
	# User Pages (Profile, Profile update)
	url(r'^user/', include('users.urls', namespace='users')),


	# Sign Up Page
	url(r'^signup/$', SignUpView.as_view(), name='signup'),
	# Login Page
	url(r'^login/(\?redirect_to=(?P<redirect_to>[^<>\'"@]*/))?$', LoginView.as_view(), name='login'),
	# Logout Url
	url(r'^logout/$', LogoutView.as_view(), name='logout'),

	
	# Accounts Settings
	url(r'^accounts/', include('accounts.urls', namespace='accounts')),
	# User Settings
	url(r'^settings/', include('settings.urls', namespace='settings')),


	# User Comments
	url(r'^comment/', include('comments.urls', namespace='comments')),


	# Admin web interface
	url(r'^admin/', include(admin.site.urls)),


	# Site navigation when js is disabled.
	url(r'^navigation/$', NavigationView.as_view(), name='navigation'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# ----------------------------------------------------------------------------------------

ulo/posts/urls.py
"""
Posts URL Configuration
"""

# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------

# Standard library imports
from __future__ import unicode_literals

# Core django imports
from django.conf.urls import include, url

# Thrid party app imports

# Project imports
from . import views

# ----------------------------------------------------------------------------------------




# ----------------------------------------------------------------------------------------

urlpatterns = [

	# Post Form
	url(r'^$', views.PostView.as_view(), name='post'),
	# Image post handler
	url(r'^image/$', views.PostImageView.as_view(), name='image'),
	# Video post handler
	url(r'^video/$', views.PostVideoView.as_view(), name='video'),

	# Users Post
	url(r'^(?P<pk>[\d]+)/$', views.PostDetailView.as_view(), name='detail'),
	url(r'^(?P<pk>[\d]+)/update/$', views.PostUpdateView.as_view(), name='update'),
	url(r'^(?P<pk>[\d]+)/delete/$', views.PostDeleteView.as_view(), name='delete'),

	# Vote on a post
	url(r'^(?P<pk>[\d]+)/vote/$', views.PostVoteView.as_view(), name='vote'),

	# Comment on a post
	url(r'^(?P<post_id>[\d]+)/comment/$', views.PostCommentView.as_view(), name='comment'),
	url(r'^(?P<pk>[\d]+)/comment/load/$', views.PostCommentLoadView.as_view(), name='comment_detail'),


	# Post actions menu when JS is disabled
	url(r'^(?P<pk>[\d]+)/actions/$', views.PostActionsView.as_view(), name='actions'),
	
	# Report this post.
	url(r'^report/complete/$', views.PostReportCompleteView.as_view(), name='report_complete'),
	url(r'^(?P<pk>[\d]+)/report/$', views.PostReportView.as_view(), name='report'),

]

# ----------------------------------------------------------------------------------------

ulo/posts/views.py
# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------

# Standard library imports
from __future__ import unicode_literals

# Core django imports
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse
from django.db import connection, IntegrityError, OperationalError, transaction
from django.db.models import F
from django.http import Http404, JsonResponse
from django.shortcuts import redirect
from django.utils.functional import cached_property
from django.utils.translation import ugettext_lazy as _
from django.views.generic.edit import DeletionMixin

# Thrid party app imports

# Project imports
from .forms import PostForm, PostUpdateForm, PostOptionForm, PostReportForm
from .models import Post, PostOption, PostVote
from .search import post_search
from .utils import IMAGE, VIDEO, DISABLED
from comments.forms import CommentForm
from comments.models import Comment
from ulo.handlers import (
	MediaUploadHandler, MemoryMediaUploadHandler, TemporaryMediaUploadHandler
)
from ulo.sessions import LinkViewsSession
from ulo.utils import (
	dictfetchmany, get_messages_json, get_cid, get_referer_path, postfetchone, 
	validate_cid
)
from ulo.viewmixins import UloLoginRequiredMixin, UloOwnerRequiredMixin
from ulo.views import UloView, UloFormView, UloUpdateView, UloUploadView

# ----------------------------------------------------------------------------------------




# POST UPLOAD VIEWS
# ----------------------------------------------------------------------------------------

class PostAttrsMixin(object):
	"""
	Define the class attributes common PostView and _PostUploadView.
	"""
	redirect_field_name = 'redirect_to'
	template_name = 'posts/post.html'
	form_class = PostForm
	option_class = PostOptionForm

# ----------------------------------------------------------------------------------------

class PostView(PostAttrsMixin, LoginRequiredMixin, UloView):
	"""
	Display the post form to the user.
	"""

	def post(self, request, *args, **kwargs):

		messages.info(request, _('Enable javascript to make a post.'))
		
		return self.get(request, *args, **kwargs)


	def get_context_data(self, **kwargs):
		
		context = super(PostView, self).get_context_data(**kwargs)
		
		context.update({
		
			'form': self.form_class(), 
			'option0': self.option_class(prefix='option0'),
			'option1': self.option_class(prefix='option1', selected='2')
		
		})
		
		return context

# ----------------------------------------------------------------------------------------

class _PostUploadView(PostAttrsMixin, LoginRequiredMixin, UloFormView):
	"""
	Handle the post request of an image or video. Post requests are first sent to 
	PostImageView or PostVideoView. Once the upload handlers have been added the request 
	is passed to this view for processing.
	"""

	post_id = None

	media_type = None


	def __init__(self, **kwargs):
		
		# Get the media type. See PostImageView and PostVideoView view_args()
		self.media_type = kwargs.get('media_type')
		
		return super(_PostUploadView, self).__init__(**kwargs)


	def get_success_url(self):
		
		return reverse('posts:detail', args=(self.post_id,))


	def get_form_kwargs(self):
		
		kwargs = super(_PostUploadView, self).get_form_kwargs()
		
		if self.request.method in ('POST', 'PUT'):
		
			kwargs.update({
		
				'media_type': self.media_type,
				'request': self.request,
				'file_field': 'file0',
				'thumbnail_field': 'thumbnail'
		
			})
		
		return kwargs


	@cached_property
	def get_options(self):
		"""
		
		Return a tuple of option forms.
		
		"""

		return (

			self.option_class(prefix='option0', data=self.request.POST),
			self.option_class(prefix='option1', data=self.request.POST, empty_permitted=True)

		)


	def option_errors(self):
		"""
		
		Return a dictionary containing the first error found for each option field.
		
		E.g. {'option0': [error], 'option1': [error]}

		"""
		
		errors = {}
		
		messages = []

		for opt in self.get_options:
			
			for item in opt.errors.items():
				
				field, msg = item
				
				messages += msg
				
				break
		
			errors.update({opt.prefix: messages})

		return errors


	def ajax_invalid(self, form):
		"""

		Add the error messages for the option forms to the response.

		"""
		
		data = super(_PostUploadView, self).ajax_invalid(form)
		
		data['errors'].update(self.option_errors())
		
		return data


	def form_valid(self, form):
		"""
		
		Save the new post and its options.

		"""

		# Get the option forms.
		option0, option1 = self.get_options

		# If the option forms are valid save all components of a post in one go.
		if option0.is_valid() and option1.is_valid():	
			
			try:

				with transaction.atomic():
				
					post = form.save()
					option0.save(post=post)
					option1.save(post=post)
				
					# Increment the counter that records the number of posts a user has.
					self.request.user.posts_count = F('posts_count')+1
					self.request.user.save()

					post_search.index_instance( post )


				# Set post_id for use by get_success_url()
				self.post_id = post.id
				
				return super(_PostUploadView, self).form_valid(form)

			except Exception as e:

				print(e)

				form.add_post_creation_error()


		# Else display the option form errors to the user.
		return self.form_invalid(form)

# ----------------------------------------------------------------------------------------

class PostMediaAttrsMixin(object):
	"""
	Define the class attributes common to PostImageView and PostVideoView.
	"""

	template_name = 'posts/post.html'
	view_handler = _PostUploadView
	form_class = PostForm


	def get_redirect_url(self):

		return reverse('posts:post')


	def get(self, request, *args, **kwargs):

		if request.is_ajax():

			return JsonResponse(

				{ 'messages': get_messages_json(request) },
				status = 403

			)

		return redirect( self.get_redirect_url() )
	
# ----------------------------------------------------------------------------------------

class PostImageView(PostMediaAttrsMixin, UloUploadView):
	"""
	NOTE: Make sure Django processes the files LAST! by making it the last element in the 
	QueryDict. Now if an error is raised because of the file the form data for all other
	fields will remain in the request object.
	"""

	view_args = {'media_type': IMAGE}

	def set_handlers(self, request):

		request.upload_handlers = [
			
			MediaUploadHandler(request=request, images=('file0',)),
			MemoryMediaUploadHandler(request=request, images=('file0',)),
			TemporaryMediaUploadHandler(request=request, images=('file0',))

		]

# ----------------------------------------------------------------------------------------

class PostVideoView(PostMediaAttrsMixin, UloUploadView):
	"""
	NOTE: Make sure Django processes the files LAST! by making it the last element in the 
	QueryDict. Now if an error is raised because of the file the form data for all other
	fields will remain in the request object.
	"""

	view_args = {'media_type': VIDEO}

	def set_handlers(self, request):

		request.upload_handlers = [
			
			MediaUploadHandler(request=request, videos=('file0',), images=('thumbnail',)),
			MemoryMediaUploadHandler(request=request, videos=('file0',), images=('thumbnail',)),
			TemporaryMediaUploadHandler(request=request, videos=('file0',), images=('thumbnail',))

		]


# END POST UPLOAD VIEWS
# ----------------------------------------------------------------------------------------

class PostDetailView(UloView):
	"""
	Render a post adding user specific information to the context for a logged in user.
	"""

	template_name = 'posts/post_detail.html'

	# Database cursor
	cursor = None


	def __init__(self, *args, **kwargs):
		
		self. cursor = connection.cursor()
		
		return super(PostDetailView, self).__init__(*args, **kwargs)


	def get(self, request, pk, *args, **kwargs):

		try:

			is_auth = request.user.is_authenticated()

			if is_auth:

				offset = 6

				self.cursor.execute(
					
					 '''SELECT

							posts_postvote.postoption_id AS vote_id,
					 		post.*

					 	FROM (

						 	SELECT

						 		posts_postoption.id AS option_id,
						 		posts_postoption.colour,
								posts_postoption.text,
								posts_postoption.icon,
								posts_postoption.count,
								post.*

						 	FROM (

							 	SELECT
									
									post.*,
									users_connection.id AS is_following
								
								FROM (

									SELECT

										posts_post.*,
										users_user.name,
										users_user.username,
										users_user.thumbnail AS user_thumbnail,
										users_user.followers_count
									
									FROM posts_post
									
									INNER JOIN users_user 
									
									ON posts_post.user_id=users_user.id
									
									WHERE posts_post.is_active=%s 
									AND posts_post.id=%s

								) AS post 

								LEFT JOIN users_connection

								ON post.user_id=users_connection.to_user_id 	
								AND users_connection.from_user_id=%s

							) AS post

							LEFT JOIN posts_postoption

							ON post.id=posts_postoption.post_id

						) AS post

						LEFT JOIN posts_postvote

						ON posts_postvote.postoption_id=post.option_id
						
						AND posts_postvote.user_id=%s
						
					''', [True, pk, request.user.id, request.user.id]
				
				)
			
			else:

				offset = 5

				self.cursor.execute(

					 '''SELECT

					 		posts_postoption.id AS option_id,
							posts_postoption.colour,
							posts_postoption.text,
							posts_postoption.icon,
							posts_postoption.count,
							post.*

					 	FROM (
		
							SELECT

								posts_post.*,
								users_user.name,
								users_user.username,
								users_user.thumbnail AS user_thumbnail,
								users_user.followers_count
							
							FROM posts_post
							
							INNER JOIN users_user 
							
							ON posts_post.user_id=users_user.id
							
							WHERE posts_post.is_active=%s 
							AND posts_post.id=%s

						) AS post

ulo/templates/posts/post_actions.html
{% extends base_template %}
{% load staticfiles i18n %}


{% block title %}Actions{% endblock title %}


{% block css %}
	<link class="css_file" href="{% static 'css/posts/post_actions.css' %}" rel="stylesheet" type="text/css">
{% endblock css %}


{% block content %}
<div id="post_actions">

	<div class="header">
			
		<a class="back" href="{{ back_url }}">
				
			<span class="icon icon_left_arrow"></span>
			<span class="hide">Back to post</span>

		</a>
		
		<h1 class="thin ellipsis">Post actions</h1>

	</div>


	<div class="summary">
		
		<img src="{% static post.thumbnail.url %}">

		<h2 class="thin">{{ post.title }}</h2>
		
	</div>
	

	<ul class="actions_menu">
		
		{% if is_own_post %}
		
			<li>

				<a href="{% url 'posts:update' post.id %}">Edit</a>

			</li>

			<li>

				<a href="{% url 'posts:delete' post.id %}">Delete</a>

			</li>
		
		{% else %}
		
			<li>

				<a href="{% url 'posts:report' post.id %}" title="Report">Report</a>

			</li>
		
		{% endif %}
		
	</ul>


</div>
{% endblock content %}

ulo/templates/posts/post_detailv1.html
{% extends base_template %}
{% load staticfiles i18n ulo_humanise %}


{% block title %}{{ post.title }}{% endblock title %}


{% block css %}
	<link class="css_file" href="{% static 'css/posts/post_detail.css' %}" rel="stylesheet" type="text/css">
{% endblock css %}


{% block content %}

<div id="post_detail">
<div class="post">
<!-- <p>&#x1F603;</p> -->
	
	<!-- POST HEADER -->
	<div class="post_header">

		<div class="user_actions">
			
			{% if is_own_post %}
			
				<a class="edit_post icon" href="{% url 'posts:update' post.id %}" title="Edit Post">
					<span class="hide">Edit</span>
				</a>
			
			{% else %}
			
				<div class="user_connection_count">
					<span class="abbr_count med">{{ post.followers_count|abbreviate }}</span>
					<span class="full_count lrg">{{ post.followers_count }}</span>
				</div>
			
				{% if post.is_following == None %}
			
				<a class="connect" data-ac="follow" href="{% url 'users:follow' post.user_id %}" title="Follow">
					<span class="icon icon_follow"></span>Follow
				</a>
			
				{% else %}
			
				<a class="connect" data-ac="unfollow" href="{% url 'users:unfollow' post.user_id %}" title="Unfollow">
					<span class="icon icon_unfollow"></span>Unfollow
				</a>
			
				{% endif %}
			
			{% endif %}
		
		</div>

		<div class="user_profile">
			
			<a data-apl="true" href="{% url 'users:profile' post.username %}" title="Profile">
			
				<img class="user_thumbnail" src="{{ MEDIA_URL }}{{ post.user_thumbnail }}">

				<div class="user_names">
					
					<h2 class="row name ellipsis">{{post.name}}</h2>
					<span class="row username ellipsis">@{{post.username}}</span>
					
				</div>

			</a>

		</div>

	</div>
	<!-- END POST HEADER -->


	<!-- POST BODY-->
	<div class="post_body">
		
		{% if post.media_type == VIDEO %}
		
		<div class="video">
			<video controls>
				<source src="{{ MEDIA_URL }}{{ post.file0 }}" type="video/mp4">
				Your browser does not support video playback.
			</video>
		</div>
		
		{% else %}

		<div class="image">
			<img src="{{ MEDIA_URL }}{{ post.file0 }}">
		</div>
		
		{% endif %}
	</div>
	<!-- END POST BODY-->


	<!-- POST FOOTER-->
	<div class="post_footer">

		<!-- PANEL 1 -->
		<div class="panel">
			
			<div class="post_published">
				<span class="sm">{{ post.published|elapsed_time }}</span>
				<span class="med lrg">{{ post.published|short_date }}</span>
			</div>
			
			<h1 class="post_title">{{ post.title }}</h1>
		
		</div>
		<!-- END PANEL 1 -->


		<!-- PANEL 2 -->
		{% if post.description != '' %}
		<div class="panel">
			
			<div id="post_description">{{ post.description }}</div>
			
			<button id="toggle_description" class="icon" type="button" data-toggle="post_description">
				<span class="hide">Toggle Description</span>
			</button>
		
		</div>
		{% endif %}
		<!-- END PANEL 2 -->


		<!-- PANEL 3 -->
		<div class="post_actions panel">
			
			{% if is_own_post == False %}
			<div class="post_actions_menu">
				
				<a class="icon post_menu_btn" href="{% url 'posts:actions' post.id %}" title="Post Actions" data-item-id="{{ post.id }}">
				
					<span class="hide">Post Actions</span>
				
				</a>

			</div>
			{% endif %}

			<div class="post_votes">

				<div id="mobile_data" class="hide">
					<div class="centre box_border"></div>
					<span class="caret_down"></span>
				</div>

				<form class="post_votes_form" action="{% url 'posts:vote' post.id %}" method="get">
		
				{% for option in post.options %}<div class="vote">

					{% if option.vote_id == None %}

						<button {% if option.icon %}class="vote icon {{ option.icon }}"{% else %}class="vote" style="background-color:{{ option.colour }}"{% endif %} data-count="{{ option.count }}" name="vote" value="{{ option.option_id }}" type="submit">
						</button>
					
					{% else %}
					
						<input type="hidden" name="voted" value="{{ option.vote_id }}">

						<button {% if option.icon %}class="vote selected icon {{ option.icon }}"{% else %}class="vote selected" style="background-color:{{ option.colour }}"{% endif %} data-count="{{ option.count }}" name="vote" value="{{ option.option_id }}" type="submit">
						</button>
					
					{% endif %}

					<div class="vote_data ellipsis">

						<span class="abbr_count sm med">{{ option.count|abbreviate }}</span>
						<span class="full_count lrg">{{ option.count }}</span>
						<span class="vote_text">{{ option.text }}</span>

					</div>

					</div>{% endfor %}
		
				</form>

			</div>

		</div>
		<!-- END PANEL 3 -->


		<!-- PANEL 4 -->
		<div id="sparkbar" class="panel" data-count-total="{{ count_total }}">
			
			{% for option in post.options %}
			
			<span class="sparkline" style="width:{{ option.count|percent:count_total }}%; background-color:{{ colours|index:forloop.counter0 }}"></span>
			
			{% endfor %}
		
		</div>
		<!-- END PANEL 4 -->


		<!-- PANEL 5 -->
		<div class="post_meta" class="panel bold">
			
			<div class="post_comment_count">
				<span class="abbr_count sm">{{ post.comments_count|abbreviate }}</span>
				<span class="full_count med lrg">{{ post.comments_count }}</span>
				 comment{% if post.comments_count != 1 %}s{% endif %}
			</div>
			
			<div class="post_view_count">
				<span class="abbr_count sm">{{ post.views|abbreviate }}</span>
				<span class="full_count med lrg">{{ post.views }}</span>
				view{% if post.views != 1 %}s{% endif %}
			</div>
		
		</div>
		<!-- END PANEL 5 -->


		<!-- PANEL 6 -->
		<div id="comment_form_container" class="panel">
			
			<form id="comment_form" action="{% url 'posts:comment' post.id %}" method="post">
				{% csrf_token %}
				{{ form.post_id }}
				{{ form.comment }}
			</form>

		</div>
		<!-- END PANEL 6 -->
		

		<!-- PANEL 7 -->
		<div id="comments_container" class="panel" data-profile-url="{% url 'users:profile' '000' %}">

			<noscript><p>Enable javascript to load comments for this post.</p></noscript>
			<div id="comment_modal" class="modal hide" data-close-modal="true"></div>

		</div>
		<!-- END PANEL 7 -->


		{% if post.comments_count != 0 %}
		<button id="load_comments" class="hide" data-action="{% url 'posts:comment_detail' post.id %}" disabled="true" type="button">Load comments</button>
		{% endif %}
		
	</div>
	<!-- END POST FOOTER-->

	{% if post_view == False %}
	<!-- POST ACTIONS MENU -->
	<div id="post_menu" class="hide">
		
		<ul class="actions_menu">
			<li>
				<button id="share_post" class="actions_btn" data-url="#" title="Share">
					<span class="icon"></span>
					<span class="text">Share</span>
				</button>
			</li>
		
			<li>
				<button id="report_post" class="actions_btn" data-url="{% url 'posts:report' '000' %}" title="Report">
					<span class="icon"></span>
					<span class="text">Report</span>
				</button>
			</li>
		</ul>
	
	</div>
	<!-- END POST ACTIONS MENU -->


	<!-- COMMENT ACTIONS MENU -->
	<div id="comment_menu" class="hide">
		
		<ul class="actions_menu">
			<li class="user_action">
				<button id="report_comment" class="actions_btn" data-url="{% url 'comments:comment_report' '000' %}" data-close-modal="true" type="button">
					<span class="icon" data-close-modal="true"></span>
					<span class="text" data-close-modal="true">Report</span>
				</button>
			</li>
		
			<li class="owner_action">
				<form id="delete_comment_form" method="post">
					{% csrf_token %}
					<button id="delete_comment_submit" class="actions_btn" data-url="{% url 'comments:comment_delete' '000' %}" data-close-modal="true" type="submit">
						<span class="icon" data-close-modal="true"></span>
						<span class="text" data-close-modal="true">Delete</span>
					</button>
				</form>
			</li>
		
		</ul>

	</div>
	<!-- END COMMENT ACTIONS MENU -->
	{% endif %}

</div>
</div>
{% endblock content %}

{% block js %}
	<script class="js_file" src="{% static 'js/users/utils.js' %}"></script>
	<script class="js_file" src="{% static 'js/posts/post_detail.js' %}"></script>
{% endblock js %}

ulo/templates/posts/post_report.html
{% extends base_template %}
{% load staticfiles i18n %}


{% block title %}Report{% endblock title %}


{% block css %}
	<link class="css_file" href="{% static 'css/posts/post_report.css' %}" rel="stylesheet" type="text/css">
{% endblock css %}


{% block content %}
<div id="post_report">

	<div class="centre" data-close-pip="true">

		<div class="wrapper{% if request.is_ajax == False %} fill{% endif %}">

			<div class="header">

				{% if request.is_ajax %}

				<span class="back icon icon_cross" data-close-pip="true"></span>

				{% else %}

				<a class="back" href="{% url 'posts:actions' pk %}" title="Back to post actions">
										
					<span class="icon icon_left_arrow"></span>

					<span class="hide">Back to post actions</span>
				
				</a>

				{% endif %}
				
				<h1 class="thin ellipsis">Report this post</h1>
			
			</div>


			{% if request.is_ajax == False %}

			<div class="summary">

				<img src="{{ form.post.thumbnail.url }}">
				
				<h2 class="thin">{{ form.post.title }}</h2>

			</div>

			{% endif %}


			<form id="post_report_form" action="{% url 'posts:report' pk %}"  method="post">
				
				{% csrf_token %}
				
				{{ form.pip }}


				{% if form.non_field_errors %}
				<div id="post_report_form_errors" class="form_errors">

					{% for error in form.non_field_errors %}
					<p class="validation error">{{ error }}</p>
					{% endfor %}

				</div>
				{% endif %}


				<div class="field">

					<p class="help_text bold">{{ form.issue.help_text }}</p>

					<div id="issue_container">

						{% for error in form.issue.errors %}
							<p class="validation error">{{ error }}</p>
						{% endfor %}

						{{ form.issue }}
					
					</div>

				</div>
				

				<div class="field">

					<p class="help_text bold">{{ form.information.help_text }}</p>

					<div id="information_container">

						{% for error in form.information.errors %}
							<p class="validation error">{{ error }}</p>
						{% endfor %}

						<div class="text_field">{{ form.information }}</div>
					
					</div>

				</div>


				<div class="submit_container">

					<input id="post_report_submit" name="submit" type="submit" value="Report">
				
				</div>


			</form>

		</div>

	</div>

</div>
{% endblock content %}


{% block js %}
	<script class="js_file" src="{% static 'js/posts/post_report.js' %}"></script>
{% endblock js %}

ulo/templates/posts/post_reportv1.html
{% extends base_template %}
{% load staticfiles i18n %}


{% block title %}Report{% endblock title %}


{% block css %}
	<link class="css_file" href="{% static 'css/posts/post_report.css' %}" rel="stylesheet" type="text/css">
{% endblock css %}


{% block content %}
<div id="post_report" data-close-modal="true">
	<div class="centered">

		<div class="header">
			{% if request.is_ajax == True %}
			<button class="icon" type="button" data-close-modal="true">
				<span class="hide">Close</span>
			</button>
			{% else %}
			<a href="{% url 'posts:actions' form.post_id %}" class="icon" title="Back to post actions">
				<span class="hide">Back to post actions</span>
			</a>
			{% endif %}
			<h1 class="title">Report</h1>
		</div>

		{% if form.post %}
		<div class="summary header">
			<img class="post_thumbnail" src="{{ form.post.thumbnail.url }}">
			<h2 class="post_title">{{ form.post.title }}</h2>	
		</div>
		{% endif %}

		<div class="panel">

			{% for error in form.non_field_errors %}
			<p class="error">{{ error }}</p>
			{% endfor %}

			{% for error in form.post_id.errors %}
			<p class="error">{{ error }}</p>
			{% endfor %}

			<form id="post_report_form" action="{% url 'posts:report' form.post_id %}"  method="post">
				{% csrf_token %}
				{{ form.pip }}	

				<div id="issue_container">
					<p class="help_text bold">{{ form.issue.help_text }}</p>
					{% for error in form.issue.errors %}
					<p class="error">{{ error }}</p>
					{% endfor %}
				</div>
				{{ form.issue }}

				
				<div id="information_container">
					<p class="help_text bold">{{ form.information.help_text }}</p>
					{% for error in form.information.errors %}
					<p class="error">{{ error }}</p>
					{% endfor %}
				</div>
				{{ form.information }}

				<input id="post_report_submit" name="submit" type="submit" value="Report">

			</form>
		</div>

	</div>
</div>
{% endblock content %}


{% block js %}
	<script class="js_file" src="{% static 'js/posts/post_report.js' %}"></script>
{% endblock js %}