ulo/accounts/urls.py
"""
Accounts URL Configuration
"""

# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------

# Standard library imports
from __future__ import unicode_literals

# Core django imports
from django.conf.urls import include, url

# Thrid party app imports

# Project imports
from . import views

# ----------------------------------------------------------------------------------------




# ----------------------------------------------------------------------------------------

urlpatterns = [

	# Email verification
	url(r'^verification/(?P<token>[^<>\'"@]+)/$',
		views.EmailVerificationView.as_view(), name='verification'),
	url(r'^resend_verification/$',
		views.ResendEmailVerificationView.as_view(), name='resend_verification'),


	# Password reset
	url(r'^password_reset/$', 
		views.PasswordResetBeginView.as_view(), name='password_reset_begin'),
	url(r'^password_reset/email/$', 
		views.PasswordResetEmailView.as_view(), name='password_reset_email'),
	url(r'^password_reset/sent/$', 
		views.PasswordResetSentView.as_view(), name='password_reset_sent'),
	url(r'^password_reset/(?P<token>[^<>\'"@]+)/$', 
		views.PasswordResetView.as_view(), name='password_reset'),


	# Not my account
	url(r'^not_my_account/confirmed/$',
		views.NotMyAccountConfirmedView.as_view(), name='not_my_account_confirmed'),
	url(r'^not_my_account/$',
		views.NotMyAccountNoUserView.as_view(), name='not_my_account_no_user'),
	url(r'^not_my_account/(?P<token>[^<>\'"@]+)/$',
		views.NotMyAccountView.as_view(), name='not_my_account'),


	# Token expired
	url(r'^token_expired/$', views.TokenExpiredView.as_view(), name='token_expired'),
	

	# Account Deactivation.
	url(r'^deactivate/$', views.DeactivateAccountView.as_view(), name='deactivate'),
	url(r'^deactivated/$', views.DeactivatedAccountView.as_view(), name='deactivated')

]

# ----------------------------------------------------------------------------------------

ulo/config/urls.py
# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------

# Standard library imports

# Core django imports
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

# Thrid party app imports

# Project imports
from generics.views import HomeAuthView, NavigationView
from users.views import LoginView, LogoutView, SignUpView

# TO SERVE MEDIA FILES IN DEVELOPMENT ONLY
from django.conf.urls.static import static

# ----------------------------------------------------------------------------------------




# ----------------------------------------------------------------------------------------

urlpatterns = [

	# TESTING!!!!
	url(r'^search/', include('search.urls', namespace='search')),


	# Landing Page
	url(r'^$', HomeAuthView.as_view(), name='home'),


	# User Posts (Post detail, Post form)
	url(r'^post/', include('posts.urls', namespace='posts')),
	# User Pages (Profile, Profile update)
	url(r'^user/', include('users.urls', namespace='users')),


	# Sign Up Page
	url(r'^signup/$', SignUpView.as_view(), name='signup'),
	# Login Page
	url(r'^login/(\?redirect_to=(?P<redirect_to>[^<>\'"@]*/))?$', LoginView.as_view(), name='login'),
	# Logout Url
	url(r'^logout/$', LogoutView.as_view(), name='logout'),

	
	# Accounts Settings
	url(r'^accounts/', include('accounts.urls', namespace='accounts')),
	# User Settings
	url(r'^settings/', include('settings.urls', namespace='settings')),


	# User Comments
	url(r'^comment/', include('comments.urls', namespace='comments')),


	# Admin web interface
	url(r'^admin/', include(admin.site.urls)),


	# Site navigation when js is disabled.
	url(r'^navigation/$', NavigationView.as_view(), name='navigation'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# ----------------------------------------------------------------------------------------

ulo/posts/urls.py
"""
Posts URL Configuration
"""

# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------

# Standard library imports
from __future__ import unicode_literals

# Core django imports
from django.conf.urls import include, url

# Thrid party app imports

# Project imports
from . import views

# ----------------------------------------------------------------------------------------




# ----------------------------------------------------------------------------------------

urlpatterns = [

	# Post Form
	url(r'^$', views.PostView.as_view(), name='post'),
	# Image post handler
	url(r'^image/$', views.PostImageView.as_view(), name='image'),
	# Video post handler
	url(r'^video/$', views.PostVideoView.as_view(), name='video'),

	# Users Post
	url(r'^(?P<pk>[\d]+)/$', views.PostDetailView.as_view(), name='detail'),
	url(r'^(?P<pk>[\d]+)/update/$', views.PostUpdateView.as_view(), name='update'),
	url(r'^(?P<pk>[\d]+)/delete/$', views.PostDeleteView.as_view(), name='delete'),

	# Vote on a post
	url(r'^(?P<pk>[\d]+)/vote/$', views.PostVoteView.as_view(), name='vote'),

	# Comment on a post
	url(r'^(?P<post_id>[\d]+)/comment/$', views.PostCommentView.as_view(), name='comment'),
	url(r'^(?P<pk>[\d]+)/comment/load/$', views.PostCommentLoadView.as_view(), name='comment_detail'),


	# Post actions menu when JS is disabled
	url(r'^(?P<pk>[\d]+)/actions/$', views.PostActionsView.as_view(), name='actions'),
	
	# Report this post.
	url(r'^report/complete/$', views.PostReportCompleteView.as_view(), name='report_complete'),
	url(r'^(?P<pk>[\d]+)/report/$', views.PostReportView.as_view(), name='report'),

]

# ----------------------------------------------------------------------------------------

ulo/users/urls.py
"""
Users URL Configuration
"""

# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------

# Standard library imports
from __future__ import unicode_literals

# Core django imports
from django.conf.urls import include, url

# Thrid party app imports

# Project imports
from . import views

# ----------------------------------------------------------------------------------------




# ----------------------------------------------------------------------------------------

urlpatterns = [

	url(r'^available/(?P<username>[\w]+)/$', views.UsernameAvailableView.as_view(), name='available'),

	# User Profile Edit Page
	url(r'^update/$', views.ProfileUpdateView.as_view(), name='profile_update'),
	url(r'^(?P<pk>[\d]+)/image/update/$', views.ProfileUpdateImageView.as_view(), name='profile_update_image'),
	url(r'^(?P<pk>[\d]+)/image/delete/$', views.ProfileDeleteImageView.as_view(), name='profile_delete_image'),


	# Follow User
	url(r'^follow/(?P<pk>[\d]+)/$', views.FollowUserView.as_view(), name='follow'),
	# UnFollow User
	url(r'^unfollow/(?P<pk>[\d]+)/$', views.UnFollowUserView.as_view(), name='unfollow'),


	# User Profile Page: username regex pattern used in users.models.User
	url(r'^(?P<username>[\w]+)/$', views.ProfileView.as_view(), name='profile'),
	# User's followers
	url(r'^(?P<username>[\w]+)/followers/$', views.ProfileFollowersView.as_view(), name='followers'),
	# User's following
	url(r'^(?P<username>[\w]+)/following/$', views.ProfileFollowingView.as_view(), name='following'),
	
]

# ----------------------------------------------------------------------------------------

ulo/users/models.py
# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------

# Standard library imports
from __future__ import unicode_literals

# Core django imports
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.backends import ModelBackend
from django.contrib.auth.hashers import check_password
from django.contrib.auth.models import (

	AbstractBaseUser, BaseUserManager, PermissionsMixin

)
from django.core import validators
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone
from django.utils.crypto import salted_hmac
from django.utils.translation import ugettext_lazy as _

# Thrid party app imports

# Project imports
from .search import user_search
from .utils import (

	BLOCKS, BLOCK_LEVELS, DEFAULT_PROFILE_PICTURE, DEFAULT_PROFILE_THUMBNAIL, GENDERS, 
	NO_BLOCK, NOT_VERIFIED

)
from ulo.models import UloModel, UloUserModel

# ----------------------------------------------------------------------------------------




# ----------------------------------------------------------------------------------------

class UserModelBackend(ModelBackend):
	"""
	User authentication backend.
	https://docs.djangoproject.com/en/1.9/topics/auth/customizing/#auth-custom-user
	If a backend raises a PermissionDenied exception, authentication will immediately 
	fail. Django will not check the backends that follow.
	"""

	def authenticate(self, email=None, password=None, **kwargs):

		UserModel = get_user_model()
		
		if email == None:

			email = kwargs.get(UserModel.USERNAME_FIELD)

		try:
		
			# Natural key will be the field defined by the 'USERNAME_FIELD'
			user = UserModel._default_manager.get_by_natural_key(email)

			if user.check_password(password):

				return user

		except UserModel.DoesNotExist:
		
			# Run the default password hasher to reduce the timing difference between 
			# an existing and a non-existing user (#20760).
			UserModel().set_password(password)

# ----------------------------------------------------------------------------------------

class UserManager(BaseUserManager):

	def _create_user(self, email, username, name, password, **extra_fields):
		"""
		Create a new user.
		"""
		
		# Check all required inputs are present
		if not email or not username or not name or not password:
			
			raise ValueError('Required fields missing. User was not created')
		
		# Create user instance
		user = self.model(

			email=email.strip().lower(), 
			username=username.strip().lower(), 
			name=name.strip(),
 			**extra_fields
		
		)
		
		# Hash password
		user.set_password(password)

		# Save user to database
		user.save(using=self._db)
		
		return user


	# Must list all required fields as parameters to this function
	def create_user(self, email, username, name, password, **extra_fields):
		"""
		Create a new user.
		"""
		
		extra_fields.setdefault('is_staff', False)
		
		extra_fields.setdefault('is_superuser', False)
		
		return self._create_user(email, username, name, password, **extra_fields)


	# Must list all required fields as parameters to this function
	def create_superuser(self, email, username, name, password, **extra_fields):
		"""
		Create a new super user.
		"""
		
		extra_fields.setdefault('is_staff', True)
		
		extra_fields.setdefault('is_superuser', True)


		if extra_fields.get('is_staff') is not True:
		
			raise ValueError('Superuser must have is_staff=True.')

		
		if extra_fields.get('is_superuser') is not True:
		
			raise ValueError('Superuser must have is_superuser=True.')


		return self._create_user(email, username, name, password, **extra_fields)

# ----------------------------------------------------------------------------------------




# ----------------------------------------------------------------------------------------

class User(UloUserModel, PermissionsMixin):
	
	# ------------------------------------------------------------------------------------

	def file_path(instance, filename):
		"""
		Create file path for the uploaded image
		"""
		
		return 'profile/%s/%s' %(timezone.now().strftime("%m-%y"), filename)

	# ------------------------------------------------------------------------------------


	# USER (REQUIRED) FIELDS
	# ------------------------------------------------------------------------------------

	# password is defined in AbstractBaseUser as:
	### password = models.CharField(_('password'), max_length=128)
	
	email = models.EmailField(
		
		_('email address'),
		max_length=255,
		unique=True,
		error_messages={
		
			'unique': _('This email address has already been registered.'),
		
		},
		help_text=_(
		
			'Please enter your email address.'
		
		),

	)

	username = models.CharField(

		_('username'),
		max_length=30,
		unique=True,
		validators=[
		
			validators.RegexValidator(
		
				r'^\w+$',
				_('Your username can only contain letters, numbers and underscores.'),
		
			),

		],
		error_messages={
		
			'unique': _('This username has been taken.'),
		
		},
		help_text=_(
		
			'Please choose a username. This can be changed later.'
		
		),
	
	)

	name = models.CharField(

		_('name'), 
		max_length=30,
		validators=[
	
			validators.RegexValidator(
	
				r'^[^<>\[\](){}="`\\/+_?!@#^*]+$',
				_('Your name cannot contain special characters.')
	
			),
	
		],
		help_text=_(
	
			'The name displayed on your profile page.'
	
		),

	)
	
	dob = models.DateField(

		_('birthday'),
		help_text=_("Your date of birth."),

	)

	gender = models.CharField(

		_('gender'),
		blank=True,
		max_length=1,
		choices=GENDERS

	)


	# END USER (REQUIRED) FIELDS
	# ------------------------------------------------------------------------------------


	# USER (NOT REQUIRED) FIELDS
	# ------------------------------------------------------------------------------------
	
	picture = models.ImageField(
	
		_('picture'),
		max_length=200,
		upload_to=file_path,
		default=DEFAULT_PROFILE_PICTURE
	
	)
	
	thumbnail = models.ImageField(
	
		_('thumbnail'),
		max_length=220,
		upload_to=file_path,
		default=DEFAULT_PROFILE_THUMBNAIL

	)
	
	location = models.CharField(
	
		_('location'),
		blank=True,
		max_length=200,
		help_text=_("Your current location.")
	
	)
	
	blurb = models.CharField(
	
		_('blurb'),
		blank=True,
		max_length=180,
		help_text=_(
			'Short description about you, your page, or anything you wish to promote.'
		)
	
	)
	
	# END USER (NOT REQUIRED) FIELDS
	# ------------------------------------------------------------------------------------
	

	# ACCESS FIELDS
	# ------------------------------------------------------------------------------------
	
	is_staff = models.BooleanField(
	
		_('staff status'),
		default=False,
		help_text=_('Designates whether the user can log into this admin site.'),
	
	)
	
	is_active = models.BooleanField(
	
		_('user status'),
		default=True,
		help_text=_(
			'Designates whether this user should be treated as active. '
			'Unselect this instead of deleting accounts.'
		),
	
	)
	
	is_verified = models.PositiveSmallIntegerField(
	
		_('email verified'),
		default=NOT_VERIFIED,
		help_text=_(
			'Designates whether this user has had their email address verified so that '
			'they are who they claim to be.'
		),
	
	)
	
	email_confirmed = models.BooleanField(
	
		_('email confirmation'),
		default=False,
		help_text=_(
			'Designates whether this user has confirmed thier email address.'
		),
	
	)

	block = models.CharField(
	
		_('account suspended'),
		max_length=2,
		choices=BLOCKS,
		default=NO_BLOCK,
		help_text=_(
			'Designates whether this user has had their account suspended'
		),
	
	)
	
	# END ACCESS FIELDS
	# ------------------------------------------------------------------------------------


	# INFO FIELDS
	# ------------------------------------------------------------------------------------
	
	# last_login is defined in AbstractBaseUser as:
	### last_login = models.DateTimeField(_('last login'), blank=True, null=True)

	date_joined = models.DateTimeField(
	
		_('date joined'), 
		default=timezone.now,
	
	)

	# Counters
	
	posts_count 	= models.PositiveIntegerField(_('Posts counter'), default=0)
	followers_count = models.PositiveIntegerField(_('Followers counter'), default=0)
	following_count = models.PositiveIntegerField(_('Following counter'), default=0)
	
	# END Counters

	# END INFO FIELDS
	# ------------------------------------------------------------------------------------


	# DB RELATIONSHIPS
	# ------------------------------------------------------------------------------------

	connections = models.ManyToManyField(
	
		'self', 
		symmetrical=False,
		through='Connection',
		through_fields=('from_user', 'to_user')
	
	)

	### User has a one-to-many relationship with Post.
	### User has a one-to-many relationship with PostVote.
	### User has a one-to-many relationship with PostReport.
	### User has a one-to-many relationship with Comment.

	# END DB RELATIONSHIPS
	# ------------------------------------------------------------------------------------


	objects = UserManager()

	# The name of the field used as the unique identifier
	USERNAME_FIELD = 'email'

	# must contain all required fields and is used only when creating a super user.
	# These will be the fields that the user must enter (plus USERNAME_FIELD)
	REQUIRED_FIELDS = ['username', 'name', 'location']


	class Meta:

		verbose_name = _('user')

		verbose_name_plural = _('users')


	# HELPER FUNCTIONS
	# ------------------------------------------------------------------------------------

	def get_picture(self):
		
		if self.picture == '':

			return settings.MEDIA_URL + DEFAULT_PROFILE_PICTURE

		return self.picture.url
	

	def get_thumbnail(self):

		if self.thumbnail == '':

			return settings.MEDIA_URL + DEFAULT_PROFILE_THUMBNAIL

		return self.thumbnail.url


	def get_full_name(self):

		return self.name

ulo/templates/users/profile v1.html
{% extends base_template %}
{% load staticfiles i18n ulo_humanise %}


{% block title %}{{ profile.name }} {{ profile.username }}{% endblock title %}

{% block css %}
	<link class="css_file" href="{% static 'css/uploads/upload.css' %}" rel="stylesheet" type="text/css">
	<link class="css_file" href="{% static 'css/users/profile.css' %}" rel="stylesheet" type="text/css">
{% endblock css %}

{% block content %}
<div id="profile" data-user-id="{{ profile.id }}" data-username="{{ profile.username }}">

	<div id="profile_header" class="container box_border">
		<div id="profile_container" class="cf">
			
			<div id="profile_picture">
				
				<img id="pp" src="{% static profile.get_picture %}">
				
				{% if is_own_page %}
				<button id="toggle_change_picture" class="icon icon_camera" type="button" data-toggle="change_picture">
				</button>

				<ul id="change_picture">
					<li><input accept="image/gif,image/jpeg,image/jpg,image/png" capture="capture" class="file" id="picture" name="picture" type="file"></li>
					<li><button id="delete_photo" type="button">Delete photo</button></li>
				</ul>
				{% endif %}

			</div>

			<div id="information">
				<div id="information_header">

					<div id="button_container">
						{% if is_own_page %}
							<a id="edit_profile" data-apl="true" href="{% url 'users:profile_update' %}">
								Edit Profile
							</a>
						{% else%}
							{% if is_following %}
								<a id="connect" data-ac="unfollow" href="{% url 'users:unfollow' profile.pk %}">
									<span class="icon icon_unfollow"></span>Unfollow
								</a>
							{% else %}
								<a id="connect" data-ac="follow" href="{% url 'users:follow' profile.pk %}">
									<span class="icon icon_follow"></span>Follow
								</a>
							{% endif %}

							<!-- <input type="hidden" name="http_referer" value="{{request.path_info|default_if_none:""}}"> -->

						{% endif %}
					</div>

					<div id="names">
						<h2 class="fullname bold">{{ profile.name }}</h2>
						<div class="username">@{{ profile.username }}</div>
					</div>
					
				</div>

				{% if profile.bio != '' %}
					<div id="bio">{{ profile.blurb }}</div>
				{% endif %}

				{% if profile.location != '' %}
					<div id="location"><span class="icon"></span>{{ profile.location }}</div>
				{% endif %}
			
			</div>
			
		</div>

	{% block tabs %}
		<div id="profile_tabs_container">
			<ul id="profile_tabs">
				<li class="tab">
					<a id="posts" class="active" href="{% url 'users:profile' profile.username %}">
						<span class="abbr_count bold">{{ profile.posts_count|abbreviate }}</span>
						<span class="text">posts</span>
					</a>
				</li>
				<li class="tab">
					<a id="followers" href="{% url 'users:followers' profile.username %}">
						<span class="abbr_count bold">{{ profile.followers_count|abbreviate }}</span>
						<span class="text">followers</span>
					</a>
				</li>
				<li class="tab">
					<a id="following" href="{% url 'users:following' profile.username %}">
						<span class="abbr_count bold">{{ profile.following_count|abbreviate }}</span>
						<span class="text">following</span>
					</a>
				</li>
			</ul>
		</div>

	</div>
	

	<div id="tab_content_container">
		<div id="tab_content" class="content container box_border" >
			<div id="posts_tab">
				{% for post in content %}
					<div class="post box_border">
						<div class="item">
							
							<a class="thumbnail" href="{% url 'posts:detail' post.cid %}" data-apl="true" title="Post Detail"><img src="{{ MEDIA_URL }}{{ post.file0 }}"></a>
							
							<div class="fields">
								<a class="title ellipsis bold" href="{% url 'posts:detail' post.cid %}" data-apl="true" title="Post Detail">{{ post.title }}</a>
								<div class="stats">
									<span class="published">{{ post.published|elapsed_time }}</span>
									<span class="views">{{ post.views }} views</span>
								</div>
							</div>
						
						</div>
					</div>
				{% empty %}
					<div class="empty">
						{% if is_own_page %}
							<p>Create your first <a class="bold" href="{% url 'posts:post' %}">post</a></p>
						{% else %}
							<p>@{{ profile.username }} has no posts</p>
						{% endif %}
					</div>
				{% endfor %}
			</div>
		</div>
	</div>
	{% endblock tabs %}

	{% if next_page %}
		<a id="next_page" href="{{ request.path_info }}?max_id={{ max_id }}">Next Page</a>
	{% endif %}

</div>


<div id="editor_container" class="hide modal box_border">
	<div id="editor">


		<div id="editor_header">
		
			<h2 class="ellipsis">Editor</h2>

			<button id="editor_close" class="icon icon_cross" type="button" data-close-modal="true">
				<span class="hide">Close editor</span>
			</button>
		
		</div>


		<div id="editor_body">
			
			<span class="overlay disabled"></span>

			<div id="editor_content">

<!-- 				<div class="clipping_mask" style="width: 600px; height: 450px;">

					<div class="crop" style="top: 30px; bottom: 30px; left: 30px; right: 30px;">

						<span class="loading"></span>

						<img src="https://storage.googleapis.com/imgfave/image_cache/1388048108204472.jpg">

					</div>

				</div> -->

			</div>
		
		</div>


		<div id="editor_footer">
			
			<div class="editor_control_panel">

				<div class="editor_slider_container">

					<div class="editor_slider">
						<div class="slider_container">
							<button id="scale_slider" type="button" class="icon slider">
								<span class="hide">Scale slider</span>
							</button>
						</div>

						<div class="scale_bar slider_bar_container">
							<span id="scale_slider_bar"></span>
						</div>
					</div>
				</div>

			</div>

			<div class="editor_actions">

				<button id="editor_submit" type="button">
					Submit
				</button>

			</div>

		</div>


		<div id="editor_menu">

			<button id="toggle_editor_delete" class="icon icon_down_arrow" type="button" data-toggle="editor_delete">
				<span class="hide">Editor menu</span>
			</button>

			<button id="editor_delete" class="hide" type="button">
				Delete
			</button>

		</div>


	</div>

</div>
{% endblock content %}








{% block js %}
	<!-- profile page javascript file -->
	{% if is_own_page %}
		<script class="js_file" src="{% static 'js/uploads/upload.js' %}"></script>
	{% endif %}
	<script class="js_file" src="{% static 'js/users/utils.js' %}"></script>
	<script class="js_file" src="{% static 'js/users/profile.js' %}"></script>
{% endblock js %}

ulo/templates/users/profile_update v1.html
{% extends base_template %}
{% load staticfiles i18n %}


{% block css %}
	<link class="css_file" href="{% static 'css/users/profile_update.css' %}" rel="stylesheet" type="text/css">
{% endblock css %}

{% block content %}
<div id="profile_edit">

	<div class="profile_edit_header">

		<h1>Edit Profile</h1>
		<a href="{% url 'users:profile' user.username %}">Back to profile</a>
	
	</div>

	<div id="profile_edit_form_container">

		<form id="profile_edit_form" action="{% url 'users:profile_update' %}" method="post">

			{% csrf_token %}

			{% if form.non_field_errors %}
			<div id="profile_edit_form_errors" class="form_errors">
				{% for error in form.non_field_errors %}
				<p class="validation error">{{ error }}</p>
				{% endfor %}
			</div>
			{% endif %}

			<div id="edit_names" class="box_border">
				
				<div class="row">

					<div class="col">
						<span class="bold ellipsis">{{ user.name }}&nbsp;</span>
						<span class="ellipsis">@{{ user.username }}</span>
					</div>

					<div class="col">
						<a class="bold" href="{% url 'settings:account' %}" title="Edit name and username">edit</a>
					</div>

				</div>
			</div>

			<div class="field">

				{{ form.blurb.label_tag }}

				<div id="blurb_container">

					{% for error in form.blurb.errors %}
						<p class="validation error">{{ error }}</p>
					{% endfor %}

					{{ form.blurb }}

				</div>

			</div>

			<div class="field">

				{{ form.location.label_tag }}

				<div id="location_container">

					{% for error in form.location.errors %}
						<p class="validation error">{{ error }}</p>
					{% endfor %}

					{{ form.location }}

				</div>

			</div>

			<div class="field">

				{{ form.dob.label_tag }}

				<div id="dob_container">
						
					{% for error in form.dob.errors %}
						<p class="validation error">{{ error }}</p>
					{% endfor %}

					<div class="dob_fields">{{ form.dob }}</div>

				</div>

			</div>

			<div class="field">

				{{ form.gender.label_tag }}

				<div id="gender_container">
						
					{% for error in form.gender.errors %}
						<p class="validation error">{{ error }}</p>
					{% endfor %}

					{{ form.gender }}

				</div>

			</div>

			<div id="profile_edit_submit_container">
				<input id="profile_edit_submit" name="submit" type="submit" value="Save Changes">
			</div>

		</form>

	</div>

</div>
{% endblock content %}

ulo/templates/users/profile_update.html
{% extends base_template %}
{% load staticfiles i18n %}


{% block css %}
	<link class="css_file" href="{% static 'css/users/profile_update.css' %}" rel="stylesheet" type="text/css">
{% endblock css %}

{% block content %}
<div id="profile_edit">

	<div class="centre">

		<h1 class="thin">Edit Profile</h1>
		
		<a class="back bold" href="{% url 'users:profile' user.username %}" title="Back to profile">Back to profile</a>
		

		<div class="user_names">

			<div class="edit_names">
				
				<a class="bold" href="{% url 'settings:account' %}" title="Edit name and username">edit</a>
			
			</div>
				
			<div class="names">
				
				<span class="bold ellipsis">{{ user.name }}&nbsp;</span>
				<span class="ellipsis">@{{ user.username }}&nbsp;</span>
				
			</div>

		</div>


		<form id="profile_edit_form" action="{% url 'users:profile_update' %}" method="post">

			{% csrf_token %}


			{% if form.non_field_errors %}
			<div id="profile_edit_form_errors" class="form_errors">
				{% for error in form.non_field_errors %}
				<p class="validation error">{{ error }}</p>
				{% endfor %}
			</div>
			{% endif %}


			<div class="field">

				{{ form.blurb.label_tag }}

				<div id="blurb_container">

					{% for error in form.blurb.errors %}
						<p class="validation error">{{ error }}</p>
					{% endfor %}

					{{ form.blurb }}

				</div>

			</div>


			<div class="field">

				{{ form.location.label_tag }}

				<div id="location_container">

					{% for error in form.location.errors %}
						<p class="validation error">{{ error }}</p>
					{% endfor %}

					{{ form.location }}

				</div>

			</div>


			<div class="field">

				{{ form.dob.label_tag }}

				<div id="dob_container">
						
					{% for error in form.dob.errors %}
						<p class="validation error">{{ error }}</p>
					{% endfor %}

					<div class="dob_fields cf">
						{{ form.dob }}
					</div>

				</div>

			</div>


			<div class="field">

				{{ form.gender.label_tag }}

				<div id="gender_container">
						
					{% for error in form.gender.errors %}
						<p class="validation error">{{ error }}</p>
					{% endfor %}

					{{ form.gender }}

				</div>

			</div>


			<div class="submit_container">

				<input id="profile_edit_submit" name="submit" type="submit" value="Save Changes">
			
			</div>

		</form>

	</div>

</div>
{% endblock content %}