ulo/accounts/urls.py
"""
Accounts URL Configuration
"""

# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------

# Standard library imports
from __future__ import unicode_literals

# Core django imports
from django.conf.urls import include, url

# Thrid party app imports

# Project imports
from . import views

# ----------------------------------------------------------------------------------------




# ----------------------------------------------------------------------------------------

urlpatterns = [

	# Email verification
	url(r'^verification/(?P<token>[^<>\'"@]+)/$',
		views.EmailVerificationView.as_view(), name='verification'),
	url(r'^resend_verification/$',
		views.ResendEmailVerificationView.as_view(), name='resend_verification'),


	# Password reset
	url(r'^password_reset/$', 
		views.PasswordResetBeginView.as_view(), name='password_reset_begin'),
	url(r'^password_reset/email/$', 
		views.PasswordResetEmailView.as_view(), name='password_reset_email'),
	url(r'^password_reset/sent/$', 
		views.PasswordResetSentView.as_view(), name='password_reset_sent'),
	url(r'^password_reset/(?P<token>[^<>\'"@]+)/$', 
		views.PasswordResetView.as_view(), name='password_reset'),


	# Not my account
	url(r'^not_my_account/confirmed/$',
		views.NotMyAccountConfirmedView.as_view(), name='not_my_account_confirmed'),
	url(r'^not_my_account/$',
		views.NotMyAccountNoUserView.as_view(), name='not_my_account_no_user'),
	url(r'^not_my_account/(?P<token>[^<>\'"@]+)/$',
		views.NotMyAccountView.as_view(), name='not_my_account'),


	# Token expired
	url(r'^token_expired/$', views.TokenExpiredView.as_view(), name='token_expired'),
	

	# Account Deactivation.
	url(r'^deactivate/$', views.DeactivateAccountView.as_view(), name='deactivate'),
	url(r'^deactivated/$', views.DeactivatedAccountView.as_view(), name='deactivated')

]

# ----------------------------------------------------------------------------------------

ulo/config/urls.py
# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------

# Standard library imports

# Core django imports
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

# Thrid party app imports

# Project imports
from generics.views import HomeAuthView, NavigationView
from users.views import LoginView, LogoutView, SignUpView

# TO SERVE MEDIA FILES IN DEVELOPMENT ONLY
from django.conf.urls.static import static

# ----------------------------------------------------------------------------------------




# ----------------------------------------------------------------------------------------

urlpatterns = [

	# TESTING!!!!
	url(r'^search/', include('search.urls', namespace='search')),


	# Landing Page
	url(r'^$', HomeAuthView.as_view(), name='home'),


	# User Posts (Post detail, Post form)
	url(r'^post/', include('posts.urls', namespace='posts')),
	# User Pages (Profile, Profile update)
	url(r'^user/', include('users.urls', namespace='users')),


	# Sign Up Page
	url(r'^signup/$', SignUpView.as_view(), name='signup'),
	# Login Page
	url(r'^login/(\?redirect_to=(?P<redirect_to>[^<>\'"@]*/))?$', LoginView.as_view(), name='login'),
	# Logout Url
	url(r'^logout/$', LogoutView.as_view(), name='logout'),

	
	# Accounts Settings
	url(r'^accounts/', include('accounts.urls', namespace='accounts')),
	# User Settings
	url(r'^settings/', include('settings.urls', namespace='settings')),


	# User Comments
	url(r'^comment/', include('comments.urls', namespace='comments')),


	# Admin web interface
	url(r'^admin/', include(admin.site.urls)),


	# Site navigation when js is disabled.
	url(r'^navigation/$', NavigationView.as_view(), name='navigation'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# ----------------------------------------------------------------------------------------

ulo/posts/urls.py
"""
Posts URL Configuration
"""

# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------

# Standard library imports
from __future__ import unicode_literals

# Core django imports
from django.conf.urls import include, url

# Thrid party app imports

# Project imports
from . import views

# ----------------------------------------------------------------------------------------




# ----------------------------------------------------------------------------------------

urlpatterns = [

	# Post Form
	url(r'^$', views.PostView.as_view(), name='post'),
	# Image post handler
	url(r'^image/$', views.PostImageView.as_view(), name='image'),
	# Video post handler
	url(r'^video/$', views.PostVideoView.as_view(), name='video'),

	# Users Post
	url(r'^(?P<pk>[\d]+)/$', views.PostDetailView.as_view(), name='detail'),
	url(r'^(?P<pk>[\d]+)/update/$', views.PostUpdateView.as_view(), name='update'),
	url(r'^(?P<pk>[\d]+)/delete/$', views.PostDeleteView.as_view(), name='delete'),

	# Vote on a post
	url(r'^(?P<pk>[\d]+)/vote/$', views.PostVoteView.as_view(), name='vote'),

	# Comment on a post
	url(r'^(?P<post_id>[\d]+)/comment/$', views.PostCommentView.as_view(), name='comment'),
	url(r'^(?P<pk>[\d]+)/comment/load/$', views.PostCommentLoadView.as_view(), name='comment_detail'),


	# Post actions menu when JS is disabled
	url(r'^(?P<pk>[\d]+)/actions/$', views.PostActionsView.as_view(), name='actions'),
	
	# Report this post.
	url(r'^report/complete/$', views.PostReportCompleteView.as_view(), name='report_complete'),
	url(r'^(?P<pk>[\d]+)/report/$', views.PostReportView.as_view(), name='report'),

]

# ----------------------------------------------------------------------------------------

ulo/search/urls.py
"""
Accounts URL Configuration
The `urlpatterns` list routes URLs to views.
"""

# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------

# Standard library imports
from __future__ import unicode_literals

# Core django imports
from django.conf.urls import include, url

# Thrid party app imports

# Project imports
from . import views

# ----------------------------------------------------------------------------------------




# ----------------------------------------------------------------------------------------

urlpatterns = [


	url(r'^$', views.SearchView.as_view(), name='search'),

	url(r'^autocomplete/$', views.AutocompleteView.as_view(), name='autocomplete')

]

# ----------------------------------------------------------------------------------------

ulo/settings/urls.py
"""
Settings URL Configuration
"""

# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------

# Standard library imports
from __future__ import unicode_literals

# Core django imports
from django.conf.urls import include, url

# Thrid party app imports

# Project imports
from . import views

# ----------------------------------------------------------------------------------------




# ----------------------------------------------------------------------------------------

urlpatterns = [

	url(r'^account/$', views.AccountSettingsView.as_view(), name='account'),

	url(r'^password/$', views.PasswordSettingsView.as_view(), name='password'),

	# url(r'^notifications/$',
	# 	views.NotificationSettingsView.as_view(), name='notifications'),
]

# ----------------------------------------------------------------------------------------

ulo/templates/base.html
{# base html template #}
{% load staticfiles i18n %}

<!DOCTYPE html>

<html lang="en">
  <head>

    <!-- Meta ======================================================================== -->

    <!-- Site wide Meta -->
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- used by search engines -->
    <meta name="description" content="Share images, videos and opinion polls">
    <!-- search keywords -->
    <meta name="keywords" content="social, poll, polling, voting, video, image, picture, share, sharing">
    <!-- indicates if the search engine should add this page to their results -->
    <meta name="robots" content="follow">
    <meta name="author" content="ta">

    <!-- Page specific Meta. Each tag must be given the class "meta_tag" -->
    {% block meta %}{% endblock meta %}

    <!-- END Meta ==================================================================== -->


    <!-- Page Title ================================================================== -->
    
    <title>{% block title %}Ulo{% endblock title %}</title>

    <!-- END Page Title ============================================================== -->

    
    <!-- CSS ========================================================================= -->

    <!-- Site wide CSS -->
    <link href="{% static 'css/base.css' %}" rel="stylesheet" type="text/css">

    <!-- Page specific CSS. Each link must be given the class "css_file" -->
    {% block css %}{% endblock css %}
    
    <!-- END CSS ===================================================================== -->

  </head>


  <body>
    <!-- Allow screen readers to jump over the navigation menu ======================= -->
    
    <a href="#main_content" title="Skip navigation" id="skip_nav">
      Skip navigation
    </a>
    
    <!-- End Allow screen readers to jump over the navigation menu =================== -->


    <!-- navigation ================================================================== -->

    <header role="banner">
        <div class="container">
            <nav id="nav_bar" role="navigation">
                <ul id="nav_menu">

                    <li id="nav_search" class="box_border">
                        <div id="nav_search_wrapper">

                            <form id="nav_search_form" action="{% url 'search:search' %}" method="get">

                                <button id="nav_search_close" type="button">
                                    <span class="icon icon_cross_white"></span>
                                    <span class="hide">Close</span>
                                </button>

                                <input id="nav_search_filter" type="hidden" name="filter" value="{{ search_filter_value }}">

                                <input id="nav_search_input" type="search" name="q" autofocus="autofocus" value="{{ q }}" autocomplete="off" placeholder="Search Ulo">

                                <button id="toggle_search_filters" class="disabled" type="button" data-toggle="search_filters">
                                    <span class="icon icon_down_arrow_white"></span>
                                    <span class="hide">Filters</span>
                                </button>

                                <button id="nav_search_submit" type="submit">
                                    <span class="icon icon_search"></span>
                                    <span class="hide">Search</span>
                                </button>

                            </form>

                            <ul id="search_filters">
                                <li data-value="{{ search_filters.video }}" data-icon="icon_filter_video">
                                    Videos
                                </li>
                                <li data-value="{{ search_filters.image }}" data-icon="icon_filter_image">
                                    Images
                                </li>
                                <li data-value="{{ search_filters.users }}" data-icon="icon_filter_person">
                                    Users
                                </li>
                            </ul>

                            <div id="nav_search_autocomplete" class="suggestions">

                                <div class="suggestions_wrapper">
                                
                                    <ul id="nav_post_suggestions"></ul
                                    ><ul id="nav_user_suggestions"></ul>

                                </div>
                            
                            </div>

                        </div>
                    </li>  

                    <li id="nav_links">
                        <div class="nav_links_wrapper">

                            <a id="toggle_nsm" href="{% url 'navigation' %}" data-toggle="nav_sub_menu" title="Profile and Settings" role="button">
                                <span class="icon icon_menu_white"></span>
                                <span class="hide">Profile and Settings</span>
                            </a>

                            <div id="nav_sub_menu">
                                <div class="menu_caret">
                                    <span class="caret_up">
                                        <span class="inner caret_up"></span>
                                    </span>
                                </div>
                                
                                {% block nav %}
                                <ul id="nav_ul">
                                    {% if user.is_authenticated %}
                                    <li>
                                        <a data-apl="true" href="{% url 'users:profile' user.username %}" title="Profile">
                                            Profile
                                        </a>
                                    </li>
                                    <li>
                                        <a data-apl="true" href="{% url 'posts:post' %}" title="Post">
                                            Post
                                        </a>
                                    </li>
                                    <li>
                                        <a data-apl="true" href="{% url 'settings:account' %}" title="Settings">
                                            Settings
                                        </a>
                                    </li>
                                    <li class="logout">
                                        <a href="{% url 'logout' %}" title="Log out">Log&nbsp;out</a>
                                    </li>
                                    {% else %}
                                    <li>
                                        <a data-apl="true" href="{% url 'signup' %}" title="Sign Up">
                                            Sign&nbsp;up
                                        </a>
                                    </li>
                                    <li>
                                        <a data-apl="true" href="{% url 'login' %}" title="Log in">
                                            Log&nbsp;in
                                        </a>
                                    </li>
                                    {% endif %}
                                </ul>
                                {% endblock nav %}
                            </div>
                            

                            

                        </div>
                    </li>

                    <li id="nav_logo">
                        <a data-apl="true" class="icon icon_logo" href="{% url 'home' %}" title="Home">
                            <span class="hide">Home</span>
                        </a>
                    </li>

                </ul>
            </nav>
        </div>
    </header>

    <!-- END navigation ============================================================== -->


    <!-- Main Content ================================================================ -->
    
    <div id="content_container">

        <!-- notifications =========================================================== -->

        <div id="messages_container" {% if messages %}class="show block"{% endif %}>
            <div id="messages">
             
                <div id="message_box">    
                    {% for message in messages %}
                        <p {% if message.tags %}class="{{ message.tags }}"{% endif %}>
                            {{ message }}
                        </p>
                    {% endfor %}
                </div>
                
            </div>
        </div>

        {% if user.email_confirmed == False %}
<!--             <div id="email_confirmation">
                <form id="email_confirmation_form" class="container box_border" action="{% url 'accounts:resend_verification' %}" method="get">

                    <p class="confirmation_text">
                        A confirmation message has been sent to <b>{{user.email}}</b>. Confirm your email address to complete your account registration.
                    </p>
                    
                    <button id="resend_confirmation" type="submit">
                        Resend Email Confirmation
                    </button>
                    
                    <a data-apl="true" id="change_email" class="bold" href="{% url 'settings:account' %}">
                        Change&nbsp;email&nbsp;address
                    </a>
            
                </form>
            
            </div> -->
        {% endif %}

        <!-- END notifications =========================================================== -->

        <main role="main" id="main_content" class="container" data-token-id="{{ csrf_token }}"{% if user.is_authenticated %} data-auth-id="{{ user.id }}"{% endif %}>

            {% block content %}{% endblock content %}
            
        </main>
    </div>

    <!-- END Main Content ============================================================ -->
    

    <!-- Javascript ================================================================== -->
    
    {% block base_js %}
    <!-- Site wide Javascript files -->
    <script src="{% static 'js/libraries/jquery-1.12.2.min.js' %}"></script>
    <script src="{% static 'js/polyfills/fastclick.min.js' %}"></script>
    <script src="{% static 'js/base.js' %}"></script>
    {% endblock base_js %}

    <!-- Page specific Javascript files. Each file must be given the class "js_file" -->
    {% block js %}{% endblock js %}

    <!-- END Javascript ============================================================== -->


  </body>
</html>

ulo/templates/base_ajax.html
{# base html template for ajax page loads #}

{% block nav %}
<ul id="nav_ul">
    {% if user.is_authenticated %}
    <li>
        <a data-apl="true" href="{% url 'users:profile' user.username %}" title="Profile">
            Profile
        </a>
    </li>
    <li>
        <a data-apl="true" href="{% url 'posts:post' %}" title="Post">
            Post
        </a>
    </li>
    <li>
        <a data-apl="true" href="{% url 'settings:account' %}" title="Settings">
            Settings
        </a>
    </li>
    <li class="logout">
        <a href="{% url 'logout' %}" title="Log out">Log&nbsp;out</a>
    </li>
    {% else %}
    <li>
        <a data-apl="true" href="{% url 'signup' %}" title="Sign Up">
            Sign&nbsp;up
        </a>
    </li>
    <li>
        <a data-apl="true" href="{% url 'login' %}" title="Log in">
            Log&nbsp;in
        </a>
    </li>
    {% endif %}
</ul>
{% endblock nav %}

<!-- Page specific Meta. Each tag must be given the class "meta_tag" -->
<span id="page_meta">{% block meta %}{% endblock meta %}</span>

<!-- Page specific CSS. Each link must be given the class "css_file" -->
<span id="page_css"> {% block css %}{% endblock css %}</span>

<!-- Page Title -->
<span id="page_title">{% block title %}Ulo{% endblock title %}</span>

<!-- Main Content -->
<main role="main" id="main_content" class="container">

	{% block content %}{% endblock content %}

</main>

<!-- Page specific Javascript files. Each script must be given the class "js_file" -->
<span id="page_js">{% block js %}{% endblock js %}</span>